### ISSUE TITLE
Could not detect pitch curve and vibrato

### ISSUE THREAD

**Issue by yamathcy** [skx300/ava#1]
Hello, 
When detecting pitch curve of input audio, an error occurred.
(when clicked "Get Pitch Curve")
Invalid MEX-file '/Users/[username]/Library/Application Support/MathWorks/MATLAB
AddOns/Apps/AVA/Users/luweiyang/Desktop/PhD/Stage2/AVA_matlab/f0_detection_package/yin_author/private/rsmooth.mexmaci64':
dlopen(/Users/[username]/Library/Application Support/MathWorks/MATLAB
AddOns/Apps/AVA/Users/luweiyang/Desktop/PhD/Stage2/AVA_matlab/f0_detection_package/yin_author/private/rsmooth.mexmaci64,
6): Library not loaded: @loader_path/libmex.dylib

Any detection methods (Yin, pYin (matlab), pYin (Tony)) didn't work.

How can I deal with it? 

Matlab version: R2021a (same error has occurred in R2019b)
OS: mac OS Big Sur (11.2.3)

**Comment by skx300** [comment]
Hi, sorry for late reply. Maybe you have to recompile the Yin method. https://github.com/skx300/ava/blob/master/f0_detection_package/yin_author/INSTALL
