### ISSUE TITLE
I can't find the installation file

### ISSUE THREAD

**Issue by Megan8821** [skx300/ava#2]
Hi there, I am interested in your work. But I couldn't find the installation file you wrote on readme.txt(named AVA.mlappinstall). Any place I can download it?
Thanks

**Comment by skx300** [comment]
Hi, the installation file is [ava](https://github.com/skx300/ava)/[AVA-export](https://github.com/skx300/ava/tree/master/AVA-export)/AVA.mlappinstall

**Comment by Megan8821** [comment]
Got it!! Thanks
